#include "magic.h"
#include "core/core.h"
#include "magic_gen.h"

// The constexpr uint64_t rookMagic[64] and bishopMagic[64] arrays are generated by magic_test.cpp.
// They contain the magic numbers for rook and bishop pieces on each square of the board.

uint64_t parallelDeposit(uint64_t value, uint64_t mask) {
    uint64_t result = 0ull;
    for (uint64_t valueBit = 1; mask; valueBit <<= 1) {
        auto maskBit = mask & -mask;  // Isolate the least significant set bit in mask
        mask -= maskBit;              // Remove it from mask
        result |= value & valueBit ? maskBit : 0;
    }
    return result;
}
MagicEntry::MagicEntry(bool bishop, Square square) {
    static constexpr int kMaxBlockerBits = 12;

    auto blockers = computeSliderBlockers(square, bishop);
    int blockerBits = blockers.size();
    assert(blockerBits > 0 && blockerBits <= kMaxBlockerBits);

    mask = blockers.bits();
    shift = 64 - blockerBits;
    magic = bishop ? bishopMagic[square] : rookMagic[square];

    table.resize(1ull << blockerBits, 0ull);
    for (uint64_t i = 0; i < (1ull << blockerBits); i++) {
        auto blockers = parallelDeposit(i, mask);
        auto targets = computeSliderTargets(square, bishop, blockers);
        if (auto& e = table[(blockers * magic) >> shift])
            assert(e == targets);
        else
            e = targets;
    }
}
namespace {

template <size_t... Is>
auto buildEntries(bool bishop, std::index_sequence<Is...>) {
    return std::array<MagicEntry, kNumSquares>{MagicEntry(bishop, Square(Is))...};
}

auto buildEntries(bool bishop) {
    return buildEntries(bishop, std::make_index_sequence<kNumSquares>{});
}

const int kMaxRank = kNumRanks - 1;
const int kMaxFile = kNumFiles - 1;

}  // namespace

// Initialized directly from the build functions; using these entries implies the tables are built.
std::array<MagicEntry, kNumSquares> rookEntries = buildEntries(false);
std::array<MagicEntry, kNumSquares> bishopEntries = buildEntries(true);

SquareSet rookBlockers(Square sq) {
    SquareSet result;

    // Up, Down, Right, Left
    for (auto to = sq; rank(to) < kMaxRank - 1;) result.insert(to = step(to, 0, 1));
    for (auto to = sq; rank(to) > 1;) result.insert(to = step(to, 0, -1));
    for (auto to = sq; file(to) < kMaxFile - 1;) result.insert(to = step(to, 1, 0));
    for (auto to = sq; file(to) > 1;) result.insert(to = step(to, -1, 0));

    return result;
}

SquareSet bishopBlockers(Square sq) {
    SquareSet result;

    // Up-Right, Up-Left, Down-Right, Down-Left
    for (auto to = sq; rank(to) < kMaxRank - 1 && file(to) < kMaxFile - 1;)
        result.insert(to = step(to, 1, 1));
    for (auto to = sq; rank(to) < kMaxRank - 1 && file(to) > 1;)
        result.insert(to = step(to, -1, 1));
    for (auto to = sq; rank(to) > 1 && file(to) < kMaxFile - 1;)
        result.insert(to = step(to, 1, -1));
    for (auto to = sq; rank(to) > 1 && file(to) > 1;)  //
        result.insert(to = step(to, -1, -1));

    return result;
}

SquareSet computeSliderBlockers(Square square, bool bishop) {
    return bishop ? bishopBlockers(square) : rookBlockers(square);
}

/**
 *   Computes the rook attack bitboard for a given square and blocker configuration.
 */
SquareSet computeRookTargets(Square sq, SquareSet blockers) {
    SquareSet result;

    // Up, Down, Right, Left - stop if we hit a blocker, after inserting that blocker
    for (auto to = sq; rank(to) < kMaxRank;)
        if (blockers.contains((result.insert(to = step(to, 0, 1)), to))) break;
    for (auto to = sq; rank(to) > 0;)
        if (blockers.contains((result.insert(to = step(to, 0, -1)), to))) break;
    for (auto to = sq; file(to) < kMaxFile;)
        if (blockers.contains((result.insert(to = step(to, 1, 0)), to))) break;
    for (auto to = sq; file(to) > 0;)
        if (blockers.contains((result.insert(to = step(to, -1, 0)), to))) break;

    return result;
}

/**
 *   Computes the bishop attack bitboard for a given square and blocker configuration.
 */
SquareSet computeBishopTargets(Square sq, SquareSet blockers) {
    SquareSet result;

    // Up-Right, Up-Left, Down-Right, Down-Left - stop if we hit a blocker, after inserting it
    for (auto to = sq; rank(to) < kMaxRank && file(to) < kMaxFile;)
        if (blockers.contains((result.insert(to = step(to, 1, 1)), to))) break;
    for (auto to = sq; rank(to) < kMaxRank && file(to) > 0;)
        if (blockers.contains((result.insert(to = step(to, -1, 1)), to))) break;
    for (auto to = sq; rank(to) > 0 && file(to) < kMaxFile;)
        if (blockers.contains((result.insert(to = step(to, 1, -1)), to))) break;
    for (auto to = sq; rank(to) > 0 && file(to) > 0;)
        if (blockers.contains((result.insert(to = step(to, -1, -1)), to))) break;

    return result;
}

SquareSet computeSliderTargets(Square square, bool bishop, SquareSet blockers) {
    return bishop ? computeBishopTargets(square, blockers).bits()
                  : computeRookTargets(square, blockers).bits();
}
