[package]
name = "magic"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "magic-test"
path = "src/main.rs"

[dependencies]
fen = { path = "../fen" }
square_set = { path = "../square_set" }

[dev-dependencies]
criterion = "0.5"
