[package]
name = "moves_table"
version.workspace = true
edition.workspace = true

[[bin]]
name = "moves-table-test"
path = "src/main.rs"

[dependencies]
fen = { path = "../fen" }
square_set = { path = "../square_set" }
