[package]
name = "square_set"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "square_set-test"
path = "src/main.rs"

[dependencies]
fen = { path = "../fen" }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "square_set_bench"
harness = false
